using Baubit.DI;

namespace SampleConsoleApp;

/// <summary>
/// Module registry for SampleConsoleApp.
/// The source generator will implement the Register() method to register all modules
/// annotated with [BaubitModule] in this assembly.
/// </summary>
[GeneratedModuleRegistry]
internal static partial class SampleModuleRegistry
{
    // Register() method will be generated by the source generator
}
