using Baubit.DI;

namespace Baubit.DI.Test
{
    /// <summary>
    /// Test module registry that registers all test modules.
    /// Generated code will implement the Register() method.
    /// </summary>
    [GeneratedModuleRegistry]
    internal static partial class TestModuleRegistry
    {
        // The Register() method will be generated by the source generator
    }
}
